# Generated by Django 4.1.2 on 2022-10-31 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='thumbnail',
        ),
    ]
