# Generated by Django 4.1.2 on 2022-10-31 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_product_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
        migrations.AddField(
            model_name='product',
            name='alt',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True, verbose_name=models.CharField(max_length=120, unique=True)),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
